name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore PasswordGeneratorWebApp.sln

      - name: Build
        run: dotnet build PasswordGeneratorWebApp.sln --configuration Release

      - name: Publish
        run: dotnet publish PasswordGeneratorWebApp/PasswordGeneratorWebApp.csproj --configuration Release --output ./publish

      - name: Deploy to DigitalOcean
        env:
          DO_API_TOKEN: ${{ secrets.DO_API_TOKEN }}
        run: |
          ssh root@your_digitalocean_ip "mkdir -p /var/www/passwordgenerator"
          scp -r ./publish/* root@your_digitalocean_ip:/var/www/passwordgenerator
          ssh root@your_digitalocean_ip "systemctl restart your_service_name"