name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore PasswordGeneratorWebApp/PasswordGeneratorWebApp.csproj

      - name: Build
        run: dotnet build PasswordGeneratorWebApp/PasswordGeneratorWebApp.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish PasswordGeneratorWebApp/PasswordGeneratorWebApp.csproj --configuration Release --output ./publish --no-build

      - name: Zip published output
        run: zip -r deploy.zip ./publish

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: PasswordGeneratorWebApp
          environment_name: PasswordGeneratorWebApp-env
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip