name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore PasswordGeneratorWebApp.sln

      - name: Build
        run: dotnet build PasswordGeneratorWebApp.sln --configuration Release

      - name: Publish
        run: dotnet publish PasswordGeneratorWebApp/PasswordGeneratorWebApp.csproj --configuration Release --output ./publish

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway up --ci